language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

# Will only test on Linux be default, special includes are needed for OSX
python:
    - 2.7
    - 3.5
    - 3.6

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Setup python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Install environment
  - pip install numpy pandas requests jsonschema

    # Install testing infrastructure
  - pip install pytest pytest-cov codecov

    # Install the package locally
  - pip install -e .


script:
  - pytest -v --cov=dqm_client dqm_client/tests/

notifications:
    email: false

after_success:
  - codecov
